apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: todo
  name: todo
spec:
  endpoints:
  - interval: 60s
    port: 8080-tcp
    path: /q/metrics
    scheme: http
    targetPort: 8080
  - interval: 60s
    port: 8080-tcp
    path: /q/metrics/application
    scheme: http
    targetPort: 8080
  selector:
    matchLabels:
      app: todo

