apiVersion: v1
kind: Service
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: todo-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
